### ISSUE TITLE
Plugin not initializing

### ISSUE THREAD

**Issue by issmirnov** [jakob1111/dokuwiki-plugin-flowcharts#15]
Hey there,

I installed this plugin on the latest RC of Dokuwiki (Hogfather).

I created a sample page:

```
<flow>
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;    
click A "SOMEPAGE"
</flow>
```

The page does not render. 

![Screen Shot 2020-06-18 at 4 12 01 PM](https://user-images.githubusercontent.com/5771615/85080595-7d09a080-b17e-11ea-947a-bf2beef18280.png)

Console logs show: 
```
mermaid-init.js:1 Uncaught ReferenceError: mermaidAPI is not defined
    at mermaid-init.js:1
```

I can confirm that `/plugins/flowcharts/mermaid.min.js` exists and is loading:

![Screen Shot 2020-06-18 at 4 11 06 PM](https://user-images.githubusercontent.com/5771615/85080571-66634980-b17e-11ea-98fd-a9481532e7af.png)

Can you help debug? Happy to post more logs, etc.

**Comment by issmirnov** [comment]
I edited the `mermaid-init.js` to call `mermaid.mermaidAPI.initialize`. This solves the JS issue seen in console. However, after checking server side logs:

```
2020/06/18 16:17:52 [error] 11182#11182: *11320231 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Doku_Parser_Mode_internallink' not found in /var/www/example.wiki/lib/plugins/flowcharts/syntax.php:98
Stack trace:
#0 /var/www/example.wiki/lib/plugins/flowcharts/syntax.php(72): syntax_plugin_flowcharts->p_get_instructions()
#1 /var/www/example.wiki/inc/parser/renderer.php(117): syntax_plugin_flowcharts->render()
#2 /var/www/example.wiki/inc/parserutils.php(673): Doku_Renderer->plugin()
#3 /var/www/example.wiki/inc/parserutils.php(142): p_render()
#4 /var/www/example.wiki/inc/parserutils.php(89): p_cached_output()
#5 /var/www/example.wiki/inc/html.php(305): p_wiki_xhtml()
#6 /var/www/example.wiki/inc/Action/Show.php(33): html_show()
#7 /var/www/example.wiki/inc/template.php(99): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 /var/www/example.wiki/inc/Extension/Event.php(129): call_user_func_array()
#10 /var/www/example.wiki/inc/Extension/Event.php(195): dokuwiki\Ext" while reading response header from upstream
```

Seems there's an issue with `Doku_Parser_Mode_internallink` caused by https://github.com/jakob1111/dokuwiki-plugin-flowcharts/blob/master/syntax.php#L72?

**Comment by pltcldvlpr** [comment]
Same here, using version 0.1 doesn't work either in current dokuwiki version.

**Comment by issmirnov** [comment]
Paging @jakob1111

**Comment by ghost** [comment]
@issmirnov, I purpose an issue close as my rendering problem stopped with installing latest commit on my Hogfather dokuwiki.

**Comment by issmirnov** [comment]
Confirmed, just tested and this works. Thank you for flagging.

<img width="392" alt="Screen Shot 2021-02-25 at 11 27 26 AM" src="https://user-images.githubusercontent.com/5771615/109206222-70e9d000-775c-11eb-9e05-1724f5791e31.png">
