### ISSUE TITLE
bundle .js for local retrieval

### ISSUE THREAD

**Issue by cultcom** [jakob1111/dokuwiki-plugin-flowcharts#5]
We do not allow .js to be loaded from external resources for our internal documentation.

So this plugin should include the mermaid .js sources so that they are loaded from the same host as the dokuwiki itself.

**Comment by jakob1111** [comment]
I changed the plugin accordingly. Thanks!

**Comment by cultcom** [comment]
unfortunately the path is wrong now. change it to :
'src'     =>  DOKU_BASE."lib/plugins/flowcharts/mermaid.min.js");
